CPPFLAGS = -O2 -W -Wall -Wextra -std=c++20 -DSHIFT_JIS

SOURCES = netmount-server.cpp fs.cpp fs_freebsd.cpp udp_socket.cpp slip_udp_serial.cpp serial_port.cpp logger.cpp unicode_to_ascii.cpp
HEADERS = fs.hpp udp_socket.hpp slip_udp_serial.hpp serial_port.hpp utils.hpp logger.hpp unicode_to_ascii.hpp ../shared/dos.h ../shared/drvproto.h

all: netmount-serverJ

netmount-serverJ: $(SOURCES) $(HEADERS)
	$(CXX) $(CPPFLAGS) $(SOURCES) -o $@

clean:
	$(RM) netmount-serverJ
